env:
  # Telegram
  TG_CHAT: "@MTKDUMPS"
  TG_TOKEN: ENCRYPTED[cb3d18fb6be0c5cbee739373d0a3818f693a0045928241fee2255e2eaf1721b4613c7d0751c073e0d842ee7fa0c4cd68]
  
  # Gitlab
  PUSH_TO_GITLAB: true
  GITLAB_GROUP: MTKDUMPS
  GITLAB_TOKEN: ENCRYPTED[30cc63d34179f320a5fe9e6e2b0a2496fa175132b08fc5416e380ef22a5937cc69c882e10241d812348dd6c6de4d403d]
  GITLAB_INSTANCE: gitgud.io
  
  # Private SSH Key
  PRIV_SSH_KEY: ENCRYPTED[1350adc7d21c58b00820fa0df51630e13e6b1ff287b53c1e0dda9c701b57680b0f94965428354be01cda027a7f156e79]

task:
  name: "Firmware Dump by MTKDUMPS"
  only_if: $CIRRUS_REPO_OWNER == 'kushagrasinghbisen'
  skip: $CIRRUS_BRANCH == 'main'
  auto_cancellation: $CIRRUS_BRANCH == 'autocancel'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  Set-SSH-Keys_script:
      - mkdir -p ~/.ssh
      - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
      - ssh-keyscan -t rsa $GITLAB_INSTANCE >> ~/.ssh/known_hosts
      - echo "$PRIV_SSH_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  Setup_script:
      - git config --global user.name "kushagrasinghbisen"
      - git config --global user.email "kushagrasinghbisen@gmail.com"
      - cd DumprX
      - echo "$GITLAB_TOKEN" > .gitlab_token
      - echo "$GITLAB_GROUP" > .gitlab_group
      - echo "$TG_CHAT" > .tg_chat
      - echo "$TG_TOKEN" > .tg_token
      - echo "$GITLAB_INSTANCE" > .gitlab_instance
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
